<div class='marginT10' id='chance_info' data-info-style='首发症状'>
        <div class='ptitle'>
            <span class='after-click'data-info-style='首发症状'>首发症状</span>
            <span class='before-click'data-info-style='体检情况'>体检情况</span>        
        </div>
        <div class='all-info'>
          <div class='info-tip positionR' id='patient_info_scroll'>
              <div class='positionA info-table-area visible' id='info_style_one_scroll'data-info-style='首发症状'>
                <div class='scroll-bar' id='info_style_one_scroll_bar'> </div>
                <table  style='height:100%' data-patient-id=''class='positionR' id='info_style_one_scroll_main'>
                  <tbody>
                    <tr>
                      <td>
                        首发症状：
                      </td>
                      <td>
                        病程:12
                      </td>
                    </tr>
                    <tr>
                      <td>
                        膀胱刺激症状:
                      </td>
                      <td>
                        无
                      </td>
                    </tr>
                    <tr>
                      <td>
                        梗阻症状:
                      </td>
                      <td>
                        壮
                      </td>
                    </tr>
                    <tr>
                      <td>
                         术前合并症：
                      </td>
                      <td>
                        168cm
                      </td>
                    </tr>
                    <tr>
                      <td>
                        术前伴发病：
                      </td>
                      <td>
                        56kg
                      </td>
                    </tr>
                    <tr>
                      <td>
                        既往尿路操作史：
                      </td>
                      <td>
                        广州大学城华南理工大学
                      </td>
                    </tr>
                    <tr>
                      <td>
                       其他：
                      </td>
                      <td>
                        13580427249
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <div class='positionA info-table-area invisible' id='info_style_two_scroll' data-info-style='体检情况'>
                <div class='scroll-bar' id='info_style_two_scroll_bar'></div>
                <table data-patient-id='' style='height:100%' class='positionR' id='info_style_two_scroll_main'>
                  <tbody>
                    <tr>
                      <td colspan='2'>
                        <label>直肠指检（DRE）</label>
                      </td>
                    </tr>

                    <tr>
                      <td>
                        前列腺距肛门距离：
                      </td>
                      <td>
                        23
                      </td>
                    </tr>
                    <tr>
                      <td>
                        前列腺直径：
                      </td>
                      <td>
                        54
                      </td>
                    </tr>
                    <tr>
                      <td>
                        突出于直肠高度：
                      </td>
                      <td>
                        510006
                      </td>
                    </tr>
                    <tr>
                      <td>
                         肿大程度：
                      </td>
                      <td>
                        高
                      </td>
                    </tr>
                    <tr>
                      <td>
                        中央沟：
                      </td>
                      <td>
                       无
                      </td>
                    </tr>
                    <tr>
                      <td>
                        触诊质地：
                      </td>
                      <td>
                       无
                      </td>
                    </tr>
                    <tr>
                      <td>
                        压痛：
                      </td>
                      <td>
                       无
                      </td>
                    </tr>
                    <tr>
                      <td>
                        结节：
                      </td>
                      <td>
                       无
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
          </div>
        </div>
      </div>